import {
  WiDayCloudy,
  WiDayFog,
  WiDayRain,
  WiDayRainMix,
  WiDayShowers,
  WiDaySleet,
  WiDaySnow,
  WiDaySnowThunderstorm,
  WiDaySprinkle,
  WiDayStormShowers,
  WiDaySunny,
  WiDaySunnyOvercast,
  WiDayThunderstorm,
  WiMoonWaxingCrescent4,
  WiNightAltCloudy,
  WiNightAltRain,
  WiNightAltShowers,
  WiNightAltSleet,
  WiNightAltSnow,
  WiNightAltSnowThunderstorm,
  WiNightAltSprinkle,
  WiNightAltThunderstorm,
  WiNightFog,
  WiNightRainMix,
  WiNightStormShowers,
} from "react-icons/wi";

export const WeatherCodes = [
  {
    code: 0,
    description: "Clear Sky",
    dayIcon: <WiDaySunny title="Clear Sky" />,
    nightIcon: <WiMoonWaxingCrescent4 title="Clear Sky" />,
  },
  {
    code: 1,
    description: "Mainly Clear",
    dayIcon: <WiDaySunny title="Mainly Clear" />,
    nightIcon: <WiMoonWaxingCrescent4 title="Mainly Clear" />,
  },
  {
    code: 2,
    description: "Partly Cloudy",
    dayIcon: <WiDaySunnyOvercast title="Partly Cloudy" />,
    nightIcon: <WiNightAltCloudy title="Partly Cloudy" />,
  },
  {
    code: 3,
    description: "Overcast",
    dayIcon: <WiDayCloudy title="Overcast" />,
    nightIcon: <WiNightAltCloudy title="Overcast" />,
  },
  {
    code: 45,
    description: "Fog",
    dayIcon: <WiDayFog title="Fog" />,
    nightIcon: <WiNightFog title="Fog" />,
  },
  {
    code: 48,
    description: "Depositing Rime Fog",
    dayIcon: <WiDayFog title="Fog" />,
    nightIcon: <WiNightFog title="Fog" />,
  },
  {
    code: 51,
    description: "Light Drizzle",
    dayIcon: <WiDaySprinkle title="Drizzle" />,
    nightIcon: <WiNightAltSprinkle title="Drizzle" />,
  },
  {
    code: 53,
    description: "Moderate Drizzle",
    dayIcon: <WiDaySprinkle title="Drizzle" />,
    nightIcon: <WiNightAltSprinkle title="Drizzle" />,
  },
  {
    code: 55,
    description: "Dense Drizzle",
    dayIcon: <WiDaySprinkle title="Drizzle" />,
    nightIcon: <WiNightAltSprinkle title="Drizzle" />,
  },
  {
    code: 56,
    description: "Light Freezing Drizzle",
    dayIcon: <WiDaySprinkle title="Drizzle" />,
    nightIcon: <WiNightAltSprinkle title="Drizzle" />,
  },
  {
    code: 57,
    description: "Dense Freezing Drizzle",
    dayIcon: <WiDaySprinkle title="Drizzle" />,
    nightIcon: <WiNightAltSprinkle title="Drizzle" />,
  },
  {
    code: 61,
    description: "Slight Rain",
    dayIcon: <WiDayRain title="Rain" />,
    nightIcon: <WiNightAltRain title="Rain" />,
  },
  {
    code: 63,
    description: "Moderate Rain",
    dayIcon: <WiDayRain title="Rain" />,
    nightIcon: <WiNightAltRain title="Rain" />,
  },
  {
    code: 65,
    description: "Heavy Rain",
    dayIcon: <WiDayRain title="Rain" />,
    nightIcon: <WiNightAltRain title="Rain" />,
  },
  {
    code: 66,
    description: "Light Freezing Rain",
    dayIcon: <WiDaySleet title="Freezing Rain" />,
    nightIcon: <WiNightAltSleet title="Freezing Rain" />,
  },
  {
    code: 67,
    description: "Heavy Freezing Rain",
    dayIcon: <WiDaySleet title="Freezing Rain" />,
    nightIcon: <WiNightAltSleet title="Freezing Rain" />,
  },
  {
    code: 71,
    description: "Slight Snow Fall",
    dayIcon: <WiDaySnow title="Snow" />,
    nightIcon: <WiNightAltSnow title="Snow" />,
  },
  {
    code: 73,
    description: "Moderate Snow Fall",
    dayIcon: <WiDaySnow title="Snow" />,
    nightIcon: <WiNightAltSnow title="Snow" />,
  },
  {
    code: 75,
    description: "Heavy Snow Fall",
    dayIcon: <WiDaySnow title="Snow" />,
    nightIcon: <WiNightAltSnow title="Snow" />,
  },
  {
    code: 77,
    description: "Snow Grains",
    dayIcon: <WiDaySnow title="Snow" />,
    nightIcon: <WiNightAltSnow title="Snow" />,
  },
  {
    code: 80,
    description: "Slight Rain Showers",
    dayIcon: <WiDayShowers title="Showers" />,
    nightIcon: <WiNightAltShowers title="Showers" />,
  },
  {
    code: 81,
    description: "Moderate Rain Showers",
    dayIcon: <WiDayShowers title="Showers" />,
    nightIcon: <WiNightAltShowers title="Showers" />,
  },
  {
    code: 82,
    description: "Violent Rain Showers",
    dayIcon: <WiDayStormShowers title="Showers" />,
    nightIcon: <WiNightStormShowers title="Showers" />,
  },
  {
    code: 85,
    description: "Slight Snow Showers",
    dayIcon: <WiDayRainMix title="Snow Shower" />,
    nightIcon: <WiNightRainMix title="Snow Shower" />,
  },
  {
    code: 86,
    description: "Heavy Snow Showers",
    dayIcon: <WiDayRainMix title="Snow Shower" />,
    nightIcon: <WiNightRainMix title="Snow Shower" />,
  },
  {
    code: 95,
    description: "Thunderstorm",
    dayIcon: <WiDayThunderstorm title="Thunderstorm" />,
    nightIcon: <WiNightAltThunderstorm title="Thunderstorm" />,
  },
  {
    code: 96,
    description: "Thunderstorm with Slight Hail",
    dayIcon: <WiDaySnowThunderstorm title="Snow Thunderstorm" />,
    nightIcon: <WiNightAltSnowThunderstorm title="Snow Thunderstorm" />,
  },
  {
    code: 99,
    description: "Thunderstorm with Heavy Hail",
    dayIcon: <WiDaySnowThunderstorm title="Hail Thunderstorm" />,
    nightIcon: <WiNightAltSnowThunderstorm title="Hail Thunderstorm" />,
  },
];
